### ISSUE TITLE
ollama._types.ResponseError: POST predict: Post "http://127.0.0.1:50640/completion": EOF

### ISSUE THREAD

**Issue by lzy728** [neo4j/neo4j-graphrag-python#233] opened 2024-12-12 02:04 UTC
Traceback (most recent call last):
  File "/Users/liuzhengyin/Documents/Liuzy/work/legislation/law_agent/bot/lib/rag/lightRag.py", line 35, in <module>
    rag.insert(f.read())
  File "/Users/liuzhengyin/Downloads/test/LightRAG/lightrag/lightrag.py", line 277, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
  File "/opt/anaconda3/envs/kno/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/liuzhengyin/Downloads/test/LightRAG/lightrag/lightrag.py", line 328, in ainsert
    maybe_new_kg = await extract_entities(
  File "/Users/liuzhengyin/Downloads/test/LightRAG/lightrag/operate.py", line 377, in extract_entities
    results.append(await result)
  File "/opt/anaconda3/envs/kno/lib/python3.9/asyncio/tasks.py", line 611, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/Users/liuzhengyin/Downloads/test/LightRAG/lightrag/operate.py", line 311, in _process_single_content
    final_result = await use_llm_func(hint_prompt)
  File "/Users/liuzhengyin/Downloads/test/LightRAG/lightrag/utils.py", line 127, in wait_func
    result = await func(*args, **kwargs)
  File "/Users/liuzhengyin/Downloads/test/LightRAG/lightrag/llm.py", line 590, in ollama_model_complete
    return await ollama_model_if_cache(
  File "/opt/anaconda3/envs/kno/lib/python3.9/site-packages/tenacity/asyncio/__init__.py", line 189, in async_wrapped
    return await copy(fn, *args, **kwargs)
  File "/opt/anaconda3/envs/kno/lib/python3.9/site-packages/tenacity/asyncio/__init__.py", line 111, in __call__
    do = await self.iter(retry_state=retry_state)
  File "/opt/anaconda3/envs/kno/lib/python3.9/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
  File "/opt/anaconda3/envs/kno/lib/python3.9/site-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "/opt/anaconda3/envs/kno/lib/python3.9/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
  File "/opt/anaconda3/envs/kno/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/anaconda3/envs/kno/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/anaconda3/envs/kno/lib/python3.9/site-packages/tenacity/asyncio/__init__.py", line 114, in __call__
    result = await fn(*args, **kwargs)
  File "/Users/liuzhengyin/Downloads/test/LightRAG/lightrag/llm.py", line 328, in ollama_model_if_cache
    response = await ollama_client.chat(model=model, messages=messages, **kwargs)
  File "/opt/anaconda3/envs/kno/lib/python3.9/site-packages/ollama/_client.py", line 834, in chat
    return await self._request(
  File "/opt/anaconda3/envs/kno/lib/python3.9/site-packages/ollama/_client.py", line 679, in _request
    return cls(**(await self._request_raw(*args, **kwargs)).json())
  File "/opt/anaconda3/envs/kno/lib/python3.9/site-packages/ollama/_client.py", line 624, in _request_raw
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: POST predict: Post "http://127.0.0.1:50640/completion": EOF

**Comment by willtai** [comment] 2024-12-12 08:38
Hey there @lzy728 thanks for creating an issue. Could you please respond with the following:

1. At a high level, what are you trying to achieve?
2. What did you do that resulted in the above error?
3. What have you tried yourself?

**Comment by stellasia** [comment] 2024-12-16 12:51
@lzy728 your stack trace doesn't show anything related to this package. It seems the issue is more with lightrag. So I'm closing this issue for now. If I'm mistaken, please reopen by providing the information requested by @willtai in the previous comment.

**Closed by stellasia** 2024-12-16 12:51 UTC
